INSERT INTO TrackerDB.Category (category_name, lft, rght, subCategory, parent_category) VALUES ('All', 1, 36, 0, 'null');
INSERT INTO TrackerDB.Category (category_name, lft, rght, subCategory, parent_category) VALUES ('Projects', 2, 9, 0, 'All');
INSERT INTO TrackerDB.Category (category_name, lft, rght, subCategory, parent_category) VALUES ('Dummy Project', 3, 4, 1, 'Projects');
#INSERT INTO TrackerDB.Category (category_name, lft, rght, subCategory, parent_category) VALUES ('COMP4920_Proj2', 5, 6, 1, 'Projects');
#INSERT INTO TrackerDB.Category (category_name, lft, rght, subCategory, parent_category) VALUES ('COMP9999_Proj1', 7, 8, 1, 'Projects');
INSERT INTO TrackerDB.Category (category_name, lft, rght, subCategory, parent_category) VALUES ('Tutorials', 10, 33, 0, 'All');
INSERT INTO TrackerDB.Category (category_name, lft, rght, subCategory, parent_category) VALUES ('Dummy Tutorial', 15, 16, 1, 'Tutorial');
#INSERT INTO TrackerDB.Category (category_name, lft, rght, subCategory, parent_category) VALUES ('COMP1917_W2', 17, 18, 1, 'Tutorial');
#INSERT INTO TrackerDB.Category (category_name, lft, rght, subCategory, parent_category) VALUES ('COMP1917_W3', 19, 20, 1, 'Tutorial');
#INSERT INTO TrackerDB.Category (category_name, lft, rght, subCategory, parent_category) VALUES ('COMP1917_W4', 21, 22, 1, 'Tutorial');
#INSERT INTO TrackerDB.Category (category_name, lft, rght, subCategory, parent_category) VALUES ('COMP1917_W5', 23, 24, 1, 'Tutorial');
#INSERT INTO TrackerDB.Category (category_name, lft, rght, subCategory, parent_category) VALUES ('COMP1917_W6', 25, 26, 1, 'Tutorial');
#INSERT INTO TrackerDB.Category (category_name, lft, rght, subCategory, parent_category) VALUES ('COMP1917_W8', 29, 32, 1, 'Tutorial');
#INSERT INTO TrackerDB.Category (category_name, lft, rght, subCategory, parent_category) VALUES ('COMP1917_W8Lab', 30, 31, 1, 'Tutorial');
#INSERT INTO TrackerDB.Category (category_name, lft, rght, subCategory, parent_category) VALUES ('COMP1917_W7', 27, 28, 1, 'Tutorial');
#INSERT INTO TrackerDB.Category (category_name, lft, rght, subCategory, parent_category) VALUES ('COMP1917_W9', 13, 14, 1, 'Tutorial');
#INSERT INTO TrackerDB.Category (category_name, lft, rght, subCategory, parent_category) VALUES ('COMP1917_W10', 11, 12, 1, 'Tutorial');
INSERT INTO TrackerDB.Category (category_name, lft, rght, subCategory, parent_category) VALUES ('Assignments', 34, 35, 0, 'All');
